version: "3"
services:
  mysql:
    image: mysql:8
    container_name: mysql
    volumes:
      - mysql-storage:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: devlake
      MYSQL_USER: merico
      MYSQL_PASSWORD: merico
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
    
  grafana:
    image: apache/devlake-dashboard:${DEVLAKE_VERSION}
    container_name: devlake-dashboard
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      GF_SERVER_ROOT_URL: "http://localhost:4000/grafana"
      MYSQL_DATABASE: lake
      MYSQL_USER: merico
      MYSQL_PASSWORD: merico
    restart: always
    depends_on:
      - mysql
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"

  devlake:
    image: apache/devlake:${DEVLAKE_VERSION}
    container_name: devlake
    ports:
      - 9000:8080
    restart: always
    volumes:
      - ./.env:/app/.env
      - ./logs:/app/logs
    environment:
      LOGGING_DIR: /app/logs
      API_TIMEOUT: "600s"
    depends_on:
      - mysql
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
  
  config-ui:
    image: apache/devlake-config-ui:${DEVLAKE_VERSION}
    container_name: devlake-config-ui
    ports:
      - 4000:4000
    env_file:
      - ./.env
    environment:
      DEVLAKE_ENDPOINT: devlake:8080
      GRAFANA_ENDPOINT: grafana:3000
    depends_on:
      - devlake
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"

volumes:
  mysql-storage:
  grafana-storage: